name: Sanity Checks
on:
  pull_request:
    branches:
      - '*'

jobs:

  sanity_checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Java (required for language-tool-python)
        run: |
          sudo apt-get update
          sudo apt-get install default-jre -y
          java -version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install language-tool-python

      - name: execute sanity_checks.py script
        run: python .github/workflows/sanity_checks_utcs.py